### ISSUE TITLE
@fa including a comma in the class second param

### ISSUE THREAD

**Issue by danielmarkavis** [appstract/laravel-blade-directives#22] opened 2017-10-11 11:54 UTC
@fa('facebook', 'fa-spin') 

gives 

<i class="fa fa-facebook, fa-spin" aria-hidden="true"></i>

adding a comma after "fa-facebook".

**Comment by teuunn** [comment] 2017-10-11 12:17
@danielmarkavis sure you've pulled in [latest release](https://github.com/appstract/laravel-blade-directives/releases/tag/0.5.2) (published 2 hours ago)? I cannot reproduce.

**Comment by gizburdt** [comment] 2017-10-11 12:24
Should be fixed in 0.5.2. Please run composer update :)

**Comment by danielmarkavis** [comment] 2017-10-11 12:28
Ah yes I was doing this

@fa('facebook', 'fa-spin')

but this works

@fa('facebook, fa-spin')

**Comment by gizburdt** [comment] 2017-10-11 12:32
This should work: @fa('facebook', 'fa-spin')

Just update to the newest version :)

**Closed as completed** 2017-10-11 12:37 UTC

**Comment by danielmarkavis** [comment] 2017-10-11 13:13
Yes it does now, I think I had some caching issues.
